modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="housing"
version="0.2.2"
displayName="housing"
credits="by cedrou"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/housing"
updateJSONURL="https://raw.githubusercontent.com/cedr0u/housing/_others_/update.json"
logoFile="logo.png"
authors="cedrou"
description='''
Housing just chilling
'''

[[dependencies.housing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




